(cl:defpackage usc_mrp-srv
  (:use )
  (:export
   "SETUSERVIEW"
   "<SETUSERVIEW-REQUEST>"
   "SETUSERVIEW-REQUEST"
   "<SETUSERVIEW-RESPONSE>"
   "SETUSERVIEW-RESPONSE"
   "SETPARAM"
   "<SETPARAM-REQUEST>"
   "SETPARAM-REQUEST"
   "<SETPARAM-RESPONSE>"
   "SETPARAM-RESPONSE"
  ))

